Resources:
  Database: 
    Type: AWS::RDS::DBInstance
    Properties: 
      Engine: postgres
      DBName: db
      DBInstanceIdentifier: my-db-instance
      MasterUsername: !Sub '{{resolve:ssm:/username}}'
      MasterUserPassword: !Sub '{{resolve:ssm:/password}}'
      AllocatedStorage: "1"
      DBInstanceClass: db.t2.micro  
  
  Outputs:
    DBName: 
      Value: !Ref Database

    DBUrl:
      Value:
        Fn::Join:
          - ''
          - - jdbc:postgresql://
            - Fn::GetAtt:
                -  Database
                - Endpoint.Address
            - ':'
            - Fn::GetAtt:
                - Database
                - Endpoint.Port
            - '/'
            - !Ref DBName

    
